# Generated by Django 5.0 on 2025-10-19 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_class', models.CharField(choices=[('Nursery', 'Nursery'), ('Lower KG', 'Lower KG'), ('Upper KG', 'Upper KG')], max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuranModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_test_1', models.IntegerField(blank=True, null=True)),
                ('class_test_2', models.IntegerField(blank=True, null=True)),
                ('semester_examination', models.IntegerField(blank=True, null=True)),
                ('total_mark', models.IntegerField(blank=True, null=True)),
                ('phonics', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('writing', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('memorizing', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quran_and_Tarbiyah', to='reportcard_app.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PunctualityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_class', models.IntegerField(blank=True, null=True)),
                ('present', models.IntegerField(blank=True, null=True)),
                ('present_percent', models.FloatField(blank=True, null=True)),
                ('absent', models.IntegerField(blank=True, null=True)),
                ('absent_percent', models.FloatField(blank=True, null=True)),
                ('late', models.IntegerField(blank=True, null=True)),
                ('late_percent', models.FloatField(blank=True, null=True)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attendance', to='reportcard_app.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicaleducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_test_1', models.IntegerField(blank=True, null=True)),
                ('class_test_2', models.IntegerField(blank=True, null=True)),
                ('semester_examination', models.IntegerField(blank=True, null=True)),
                ('total_mark', models.IntegerField(blank=True, null=True)),
                ('motor_skills', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Physical_Education', to='reportcard_app.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='NumeracyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_test_1', models.IntegerField(blank=True, null=True)),
                ('class_test_2', models.IntegerField(blank=True, null=True)),
                ('semester_examination', models.IntegerField(blank=True, null=True)),
                ('total_mark', models.IntegerField(blank=True, null=True)),
                ('counting', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('arithmetic', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('shapes', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('measurment', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Numeracy', to='reportcard_app.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='holisticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.CharField(choices=[('Satisfied', 'S'), ('Progressive', 'P'), ('Needs Improvement', 'NI')], max_length=50)),
                ('assignment_completion', models.CharField(choices=[('Satisfied', 'S'), ('Progressive', 'P'), ('Needs Improvement', 'NI')], max_length=50)),
                ('behavior_with_teachers', models.CharField(choices=[('Satisfied', 'S'), ('Progressive', 'P'), ('Needs Improvement', 'NI')], max_length=50)),
                ('behavior_classmates', models.CharField(choices=[('Satisfied', 'S'), ('Progressive', 'P'), ('Needs Improvement', 'NI')], max_length=50)),
                ('discipline', models.CharField(choices=[('Satisfied', 'S'), ('Progressive', 'P'), ('Needs Improvement', 'NI')], max_length=50)),
                ('collaboration', models.CharField(choices=[('Satisfied', 'S'), ('Progressive', 'P'), ('Needs Improvement', 'NI')], max_length=50)),
                ('problem_solving', models.CharField(choices=[('Satisfied', 'S'), ('Progressive', 'P'), ('Needs Improvement', 'NI')], max_length=50)),
                ('organizational_skills', models.CharField(choices=[('Satisfied', 'S'), ('Progressive', 'P'), ('Needs Improvement', 'NI')], max_length=50)),
                ('prayer', models.CharField(choices=[('Satisfied', 'S'), ('Progressive', 'P'), ('Needs Improvement', 'NI')], max_length=50)),
                ('moral_values', models.CharField(choices=[('Satisfied', 'S'), ('Progressive', 'P'), ('Needs Improvement', 'NI')], max_length=50)),
                ('hygiene', models.CharField(choices=[('Satisfied', 'S'), ('Progressive', 'P'), ('Needs Improvement', 'NI')], max_length=50)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Holostic_Evaluation', to='reportcard_app.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ExtracurricularModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_test_1', models.IntegerField(blank=True, null=True)),
                ('class_test_2', models.IntegerField(blank=True, null=True)),
                ('semester_examination', models.IntegerField(blank=True, null=True)),
                ('total_mark', models.IntegerField(blank=True, null=True)),
                ('participation', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('teamwork', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Extra_Curricular', to='reportcard_app.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishliteracyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_test_1', models.IntegerField(blank=True, null=True)),
                ('class_test_2', models.IntegerField(blank=True, null=True)),
                ('semester_examination', models.IntegerField(blank=True, null=True)),
                ('total_mark', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('phonics', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('vocabulary', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('reading', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('writing', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='English_Literacy', to='reportcard_app.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher_Comments', to='reportcard_app.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BengaliliteracyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_test_1', models.IntegerField(blank=True, null=True)),
                ('class_test_2', models.IntegerField(blank=True, null=True)),
                ('semester_examination', models.IntegerField(blank=True, null=True)),
                ('total_mark', models.IntegerField(blank=True, null=True)),
                ('phonics', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('vocabulary', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('reading', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('writing', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bengali_Literacy', to='reportcard_app.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AwarenessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_test_1', models.IntegerField(blank=True, null=True)),
                ('class_test_2', models.IntegerField(blank=True, null=True)),
                ('semester_examination', models.IntegerField(blank=True, null=True)),
                ('total_mark', models.IntegerField(blank=True, null=True)),
                ('health', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('social', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('safety', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('mindfulness', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Awareness_Skill', to='reportcard_app.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ArtModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_test_1', models.IntegerField(blank=True, null=True)),
                ('class_test_2', models.IntegerField(blank=True, null=True)),
                ('semester_examination', models.IntegerField(blank=True, null=True)),
                ('total_mark', models.IntegerField(blank=True, null=True)),
                ('creativity', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('artistic', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('craftsmanship', models.CharField(choices=[('Exceeding Expectations', 'E'), ('Meeting Expectations', 'M'), ('Approching Expectations', 'A')], max_length=50)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Art', to='reportcard_app.studentmodel')),
            ],
        ),
    ]
