# Generated by Django 5.0 on 2025-04-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=400)),
                ('present_address', models.CharField(max_length=400)),
                ('contact_num', models.IntegerField(max_length=12)),
                ('email', models.EmailField(max_length=200)),
                ('married', models.BooleanField(default=False)),
                ('spous_name', models.CharField(max_length=100)),
                ('religon', models.CharField(choices=[('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Christianity', 'Christianity')], max_length=100)),
                ('nationality', models.BooleanField(default=True)),
            ],
        ),
    ]
