# Generated by Django 5.0 on 2025-04-10 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation')], max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('result', models.CharField(max_length=20)),
                ('group_subject', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=200)),
                ('board_university', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=200)),
                ('responsibility', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('contact_num_1', models.CharField(max_length=20)),
                ('contact_num_2', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('married', models.CharField(choices=[('married', 'Married'), ('single', 'Single')], max_length=10)),
                ('spous_name', models.CharField(blank=True, max_length=100, null=True)),
                ('religon', models.CharField(choices=[('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Christianity', 'Christianity')], max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Career/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='Signature/')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='Academic_App.personalmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Academic_App.personalmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('result', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=200)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='Academic_App.personalmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='CareerModel',
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='Academic_App.personalmodel'),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='Academic_App.personalmodel'),
        ),
    ]
