# Generated by Django 5.0 on 2025-10-11 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0003_rename_nationality_personalmodel_spouse_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='academic_app.personalmodel'),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='academic_app.personalmodel'),
        ),
        migrations.AlterField(
            model_name='referencemodel',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='academic_app.personalmodel'),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='academic_app.personalmodel'),
        ),
        migrations.AlterField(
            model_name='trainingmodel',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='academic_app.personalmodel'),
        ),
    ]
