# Generated by Django 5.0 on 2025-04-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='facultymodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='about_app/'),
        ),
    ]
