# Generated by Django 5.0 on 2025-09-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0002_alter_facultymodel_gender_alter_facultymodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymodel',
            name='education',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
