# Generated by Django 5.0 on 2025-09-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0003_facultymodel_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('grade', models.CharField(choices=[('Nursery', 'Nursery'), ('Lower KG', 'Lower KG'), ('Upper KG', 'Upper KG'), ('Grade One', 'Grade One'), ('Grade Two', 'Grade Two'), ('Grade Three', 'Grade Three'), ('Grade Four', 'Grade Four'), ('Grade Five', 'Grade Five'), ('Grade Six', 'Grade Six'), ('Grade Seven', 'Grade Seven'), ('Grade Eight', 'Grade Eight'), ('Grade Nine', 'Grade Nine'), ('O Level', 'O Level'), ('As Level', 'As Level'), ('A Level', 'A Level')], max_length=20)),
                ('message', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
